### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by grebulon** [yuvadm/free-haaretz#12]
They changed something again...

**Comment by yuvadm** [comment]
You're going to have to provide more details:

- are you on the latest version?
- is addon disabled?
- firefox/chrome?
- when do pages seem blocked?

**Comment by davidbgeek** [comment]
@grebulon In the meantime, you can get the xray chrome extension (it unblocks all sites): https://chrome.google.com/webstore/detail/xray/dgkdfehohjdbmnldpcegekjakcdjlnkg?utm_source=chrome-app-launcher-info-dialog

**Comment by grebulon** [comment]
Very latest version, it's not disabled, tested on both firefox and chrome.
I get redirect to: http://www.haaretz.co.il/vblocked which shows a message: "אתר הארץ חסום לגולשים שמשתמשים בחוסם פרסומות". The blocker is disabled of course.
xray also crapped out...

**Comment by davidbgeek** [comment]
@grebulon xray Oh! You're using the Israeli version... Haaretz.com gets unblocked by both. They probably implemented a new system on Haaretz.co.il

**Comment by yuvadm** [comment]
@grebulon you're hitting their new anti ad-block script. this isn't covered by this addons. update your Israeli Easy List in your ad blocker, the have a fix in place.

**Comment by grebulon** [comment]
Updating Easy List fixed the issue. However, I had to manually delete the redirect cookie.

**Comment by yuvadm** [comment]
yeah they also plant a nasty cookie, i think i had to do that as well. glad you got it fixed!

**Comment by grebulon** [comment]
The adblockRedirect cookie appeared again. Perhaps need to block it somehow...
![adblock](https://cloud.githubusercontent.com/assets/324996/14776715/e57a9ee8-0ad0-11e6-81e7-304e488fa990.png)

**Comment by yuvadm** [comment]
@grebulon see https://github.com/ABPIsrael/EasyListHebrew/issues/104
