### ISSUE TITLE
The FF xpi at the homepage can't be installed.

### ISSUE THREAD

**Issue by LL25255252** [yuvadm/free-haaretz#13]
The FF xpi at the homepage can't be installed.
https://github.com/yuvadm/free-haaretz

I extracted 0.7.1 version from the master.zip and it works fine.
BTW - version 0.4 worked fine for me. What are the main improvements of 0.7.1 ?
TIA.

Firefox 45.0.2
Win 7 x64

**Comment by yuvadm** [comment]
Can you explain what exactly is failing? This might have to do with the links not pointing directly to the raw files, I fixed that now.

If it's still not working, please provide more details.

**Comment by LL25255252** [comment]
Sorry for the late response, and thanks for the fix. No problems in FF now.

**Comment by yuvadm** [comment]
@LL25255252 didn't fix anything revently :) glad it works

**Comment by LL25255252** [comment]
@yuvadm It seems that you fixed it the same day I reported it (22 April) but I have forgotten to report back to this thread until today.
