### ISSUE TITLE
chrome disables after restart

### ISSUE THREAD

**Issue by benklinger** [yuvadm/free-haaretz#14]
and there is no way to enable it back.
The only solution is to upload to the Chrome Store. Is the possible / legal?

**Comment by yuvadm** [comment]
@benklinger what exactly gets disabled after restart?

**Comment by benklinger** [comment]
I can't seem to reproduce it right now, but everytime I restart Chrome the extension is disabled and can't be enabled again:
https://www.dropbox.com/s/fxi9hsgp6eot5vx/Screenshot%202016-05-30%2018.53.40.png?dl=0

**Comment by yuvadm** [comment]
@benklinger So no repro, and doesn't seem like an addon bug anyway. On a separate note you're on a *very* old version of the addon.
