### ISSUE TITLE
Works on Palemoon with 0.4 but not with 0.7.1

### ISSUE THREAD

**Issue by LL25255252** [yuvadm/free-haaretz#15]
I tweaked the install.rdf to make the extension compatible with Palemoon also.

free-haaretz 0.4 FF & PM.xpi
https://mega.nz/#!c9MwBZKK!e_GU0bt0EtD0PUppbwknnLOK06nWJ0NBMrzPkB2cyaM
Works both in FF and PM

free-haaretz 0.7.1 FF & PM.xpi 
https://mega.nz/#!lp1W0RBC!9--jhwezrFEGtfmiQRB-h73wgtVG52uOu3wUdjPHV8M
Works on FF 46.0.1
Not working on PM 26.2.2 (x64) (The site brings its paywall block)
e.g http://www.haaretz.co.il/gallery/.premium-1.2948044

To make the extension work with palemoon I just added the next lines to the install.rdf

```
 <!-- PaleMoon -->
<em:targetApplication>
  <Description>
    <em:id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</em:id>
    <em:minVersion>25.0</em:minVersion>
    <em:maxVersion>50.0</em:maxVersion>
  </Description>
</em:targetApplication>
```

BTW - The extension id has changed some months ago so you must uninstall the old extension before installing the new version (otherwise both will be installed)

Thanks in advance.

**Comment by yuvadm** [comment]
This issue seems to be stale, please reopen with further details if still not working on `v0.9`
