### ISSUE TITLE
Gracefully handle URLs with referrers

### ISSUE THREAD

**Issue by LL25255252** [yuvadm/free-haaretz#16]
As you probably know one can can subscribe to - for example -  הכתבות הנקראות באתר הארץ - and get emails with links to haaretz articles.

Suddenly these last few days the extension can't unblock the articles referred to by those emails (the paywall message is displayed after 1-2 paragraphs).

The extensions continues to work fine if I manually remove the referrer part of the the URL.

So can you please strip down the referrer part of the the URL.

e.g. http://www.haaretz.co.il/news/politics/.premium-1.3070069?utm_content=news%2Fpolitics%2F1.3070069&utm_medium=email&utm_campaign=%D7%A2%D7%9E%D7%95%D7%A1+%D7%94%D7%A8%D7%90%D7%9C&utm_source=smartfocus&utm_term=20160916-16%3A53

Comodo Icedragon 48.0.0.2 (a fork of Firefox)
free haaretz 0.7.1
Win 7 x64

Thanks in advance.

**Comment by yuvadm** [comment]
@LL25255252 if you can provide a pull request that would be great, otherwise it's going to take me a few more days before I can patch this.

**Comment by yuvadm** [comment]
Actually this is resolved now that the FF/chrome sources have been merged and use the same WebExtensions APIs.

**Comment by LL25255252** [comment]
Yes, many thanks the issue is fixed.
