### ISSUE TITLE
The new 0.9 version doesnt work on Pale Moon 27

### ISSUE THREAD

**Issue by LL25255252** [yuvadm/free-haaretz#17]
First, thanks a lot for keeping this addon alive.

Last year I left "Firefox" and now I use Palemoon (which started as a Firefox Fork a few years ago) mainly since its great 27 version (November 2016).
Free Haaretz is the only addon I have which worked before on Firefox but doesn't work or have a replacement in Palemoon.
On the new 0.9 version I get - "addon seems to be corrupt"

On Cyberfox 50.1.0 I get the same "addon seems to be corrupt"
Cyberfox with Free haaretz 0.7.1 (after updating the install.rdf) - It works. Here is the updated xpi - 
https://mega.nz/#!QkczyJaK!aoERQ6ynW-7A6pgNnFIUMzxz88wkiV7A2CMOnRC-MSk

The new 0.9 work fine with Firefox, Waterfox & Icedragon

Chrome browser - works fine
Firefox for android - haven't checked

Win 7 x64
Thanks in advance.

**Comment by yuvadm** [comment]
@LL25255252 thanks for the thorough report, of course I'll try to support this addons on as many brwosers as possible. Do you know if palemoon/cyberfox support the new WebExtensions API? Or how they expect an XPI to be packaged?

**Comment by FreedomFighterSparrow** [comment]
@LL25255252, Pale Moon and Cyberfox are completely different beasts. It
seems that:

   1. CyberFox seems to be a simpler re-packaging with a different theme,
   and follows Firefox release closely - that is, their code is rebased every
   time. Therefore, I'm surprised the addon doesn't work for you there - it
   definitely should.
   2. Pale Moon is a fork of Firefox ESR 24, so no WebExtensions. From Pale
   Moon's roadmap <https://www.palemoon.org/roadmap.shtml>:"Unlike Firefox,
   Pale Moon will continue to offer full support for XUL and XPCOM
   binary-component extensions and there is no plan to discard the current
   extension system in lieu of Chrome-like alternatives (WebExtensions)."

**Comment by yuvadm** [comment]
@FreedomFighterSparrow in that case I am not interested in continuing support for Pale Moon, the cross-browser standards are converging around WebExtensions (supported on Firefox, Chrome and Opera). Feel free to take the [old Firefox XPCOM codebase](https://github.com/yuvadm/free-haaretz/tree/f216d62f82981965a630d7a8e734a7aa48e8cde5/firefox) and fork it into a version that works on Pale Moon.

As for Cyberfox, I'm open to receiving any PR that adds compatability based on the existing code base.

**Comment by LL25255252** [comment]
I updated the install.rdf of 0.7.1 and now it works on Cyberfox (I fixed my OP).
The new Free Haaretz 0.9 has no install.rdf so I don't know how to make it compatible with Cyberfox (I get "addon seems to be corrupt").

**Comment by LL25255252** [comment]
I don't why but I succeeded this time to install  0.9 on Cyberfox. Maybe it's because this time it's Cybefox 51 (not 50) or maybe it's because this time I decided to install CF without the CTR plugin (the "Classic Theme Restorer" addon).
I'll update the title of this "issue".

**Comment by yuvadm** [comment]
@LL25255252 thanks for the update, in that case I'll go ahead and close the issue since there's nothing left to do for CF and as stated before support for PM is out of scope for this project.
