### ISSUE TITLE
0.93 xpi appears to be corrupt(?)

### ISSUE THREAD

**Issue by jorjio** [yuvadm/free-haaretz#20]
hi,
trying to install the 0.93 xpi on firefox 53 x64 for windows- 
shows "the add-on could not be installed because it appears to be corrupt"
the same xpi installed successfully on my firefox for android.

THANKS!!!

**Comment by yuvadm** [comment]
Do other versions work? Did the file download properly?

**Comment by jorjio** [comment]
I use your addon for years - it worked wonderfully - Thanks!
right now, when trying to install versions 0.9 - 0.93 on two different computers or on a fresh firefox profile it shows the corrupt issue.

what am i doing wrong?

Thanks for your time!

**Comment by yuvadm** [comment]
@jorjio one more debugging step, try downloading the chrome ZIP, renaming it to an XPI, and try installing it (it will warn about it being unsigned, let it continue). Does that work?

**Comment by jorjio** [comment]
no,
it doesn't work (renaming the chrome zip to xpi)
same error message as before "...appears to be corrupt"

thanks.

On Thu, Apr 13, 2017 at 2:58 PM, Yuval Adam <notifications@github.com<mailto:notifications@github.com>> wrote:

@jorjio<https://github.com/jorjio> one more debugging step, try downloading the chrome ZIP, renaming it to an XPI, and try installing it (it will warn about it being unsigned, let it continue). Does that work?

**Comment by yuvadm** [comment]
Reproduced this on another Windows machine. Doesn't seem to happen on Linux though.

**Comment by yuvadm** [comment]
@jorjio can you please test `v0.9.4`? BTW it doesn't reproduce for me on Windows 10 32-bit on a VM.

**Comment by jorjio** [comment]
sorry, same issue.
Now it wont install on my android firefox also (0.93 did got install successfully on android- only it forced a desktop versionof the website, and later it gave warning issue by the haaretz website itself - i guess they became aware of your addon).
btw i'm using firefox 54 - but i'm able to install unsigned extensions-  for instance from github directly..

thanks!

**Comment by jorjio** [comment]
sorry, same issue.
Now it wont install on my android firefox also (0.93 did got install successfully on android- only it forced a desktop versionof the website, and later it gave warning issue by the haaretz website itself - i guess they became aware of your addon).
btw i'm using firefox 54 - but i'm able to install unsigned extensions- for instance from github directly..

thanks!
(i accidentally closed the issue)

**Comment by yuvadm** [comment]
1. Which warning did you get? There are several possible warnings I can think of.
2. This extension is definitely signed, it's just not distributed via the Mozilla Store.
3. I still haven't pushed a version that handles mobile user agents properly, will get to it soon.

**Comment by jorjio** [comment]
1.
![1384194_10151996632088665_902938707_n](https://cloud.githubusercontent.com/assets/5610394/25567748/74e57a08-2dfd-11e7-85e2-89a36ca05b8a.jpg)
 i cant recreate this message right now  - but i downloaded from a facebook group the same one i got (attached - mine was in english).
2. excuse me, i'm completely clueless on these matters - but i red somewhere that you should compress the xpi using zip deflate, and only then sign it - i'm just throwing it out there, i dont really know what i'm talking about.
3. looking forward to your mobile version

![1384194_10151996632088665_902938707_n](https://cloud.githubusercontent.com/assets/5610394/25567717/9b62e68a-2dfc-11e7-8caa-457beac132ed.jpg)

**Comment by yuvadm** [comment]
This seems to be an old issue, I'm closing it. Please re-open this issue or a new one with further details if the latest release is buggy.
