### ISSUE TITLE
it seems the extension no longer works?

### ISSUE THREAD

**Issue by dants** [yuvadm/free-haaretz#21]
At least not for me -- I'm no longer able to access Haaretz articles (Firefox 54.0.1 / Windows 10)

**Comment by yuvadm** [comment]
@dants are you on the latest version 0.9.4?

**Comment by dants** [comment]
Yes, before posting I reinstalled to use the latest version and restarted Firefox. But now it seems my report was a false alarm: as of this morning, I'm able to again view articles in their entirety (although I believe I didn't change anything). Anyway, thanks for the quick reply and sorry for the bother.

**Comment by yuvadm** [comment]
Cool no problem. Sometimes they have weird cookies that can produce unspecified behavior. This can usually be solved by cleaning all haaretz cookies + local storage (`window.localStorage.clear()` in JS console on any haaretz page)
