### ISSUE TITLE
Comments on Haaretz stopped showing

### ISSUE THREAD

**Issue by xspy007** [yuvadm/free-haaretz#23]
For example
https://www.haaretz.co.il/news/politi/.premium-1.6012551

There suppose to be 200+ comments, but none are showing.

Turning off the extension will resume the comments list, but no article :-( 

10x

**Comment by antishok** [comment]
This has started working fine again, at least for me.  (on that specific link there are over 700 comments, it took a while to load but they showed up eventually)

**Comment by yuvadm** [comment]
The extension doesn't do any script blocking (there is some CSS element blocking, but it might be useless nowdays), so it shouldn't affect page behavior. Please make sure you're on the latest release, and double check.

Unless a specific buggy behavior can be shown, I'm inclined to close this issue.

**Comment by xspy007** [comment]
Hello

yes, a few days ago it suddenly started working again.

wonder way...

no change to the extension was made at any time.

10x, Udi

**Comment by yuvadm** [comment]
Upstream issue in that case. Closing.
