### ISSUE TITLE
Seems not to be working

### ISSUE THREAD

**Issue by guysoft** [yuvadm/free-haaretz#26]
Hey, tested on firefox 60 and does not seem to be working, try:
https://www.haaretz.co.il/food/food-news/.premium-1.6195803

**Comment by yuvadm** [comment]
That specific link is 404, and other pages work for me. Are you on the latest version of the addon?

**Comment by guysoft** [comment]
I got if from here: https://github.com/yuvadm/free-haaretz#firefox

**Comment by yuvadm** [comment]
@guysoft if you can provide further information on what is broken, please update this issue. Closing otherwise.
