### ISSUE TITLE
Problems blocking ads

### ISSUE THREAD

**Issue by Nirsch1** [yuvadm/free-haaretz#43]
1. On Firefox (Windows 10, Windows 7 and Android), When using the "uBlock Origin" add-on, trying to open a paywalled article leads to a redirection to the page https://www.haaretz.co.il/hblocked . 
2. The adding of the following lines to "uBlock Origin" -> "My Filters" doesn't help:
||www.haaretz.co.il/htz/js/inter.js
||www.themarker.com/st/c/static/heb/inter.js
3. The adding of the following cookies to F12 of Windows-Firefox doesn't work either:
document.cookie = "HtzPusr=1"
document.cookie = "TmPusr=1"

**Comment by antishok** [comment]
FWIW, I can still open paywalled articles fine, just the comments have not been showing since recently. I'm on firefox, win10.
Try maybe deleting all the site's cookies/data

**Comment by Nirsch1** [comment]
Which version of Firefox are you using?
I can't open paywalled articles in Firefox version 66.0.4 (32-bit).

BTW, I can't open paywalled articles in Chrome either [version 75.0.3770.100 (Official Build) (64-bit)].

**Comment by antishok** [comment]
I'm using FF 67.0.2 (64-bit),  I doubt it has to do with the version (as long as you're on a recent one).
And I am seeing the same behaviour in Chrome (the articles load ok, just comments are missing)

**Comment by Nirsch1** [comment]
I've added "EasyList Hebrew" to the filter-list of "uBlock Origin", and the problem seems to be solved! Thanks for your answers, antishok!

**Comment by hemulin** [comment]
@Nirsch1 Can you please provide step by step instructions?

**Comment by Nirsch1** [comment]
Hey @hemulin.
1. Go to https://filterlists.com
2. In the search bar enter: EasyList Hebrew.
3. In the "EasyList Hebrew" line, press on the button "Details".
4. Now press "Subscribe" and "OK".

That's it!
