### ISSUE TITLE
Specific article not loading

### ISSUE THREAD

**Issue by avivmu** [yuvadm/free-haaretz#44]
I'm working with firefox version 67.0.4 (64-bit), Windows 10 and also have uBlockOrigin.
Im able to view some articles, but some not.
This one works for me: https://www.haaretz.co.il/gallery/galleryfriday/.premium-MAGAZINE-1.7361690
However, this one doesn't show any content: https://www.haaretz.co.il/captain/net/.premium-1.6851274

**Comment by Nirsch1** [comment]
I bumped into this problem yesterday (27/6), but it seems to be working now.

**Comment by avivmu** [comment]
@Nirsch1 Works for me as well, I'll close this issue
