### ISSUE TITLE
Reading List

### ISSUE THREAD

**Issue by shririmps** [yuvadm/free-haaretz#9]
A significant part of the webpage is hidden by this explanation of the so called "Reading List". Although there's an X button to try and close this pop-under - it can not be closed. Also, it appears to happen on every page on the site. Perhaps it's an attempt to block the plugin users from seeing content, because when I turned off the plugin it did not appear at all.
![default](https://cloud.githubusercontent.com/assets/11624754/6795997/cf9e3840-d1f2-11e4-9185-81d447d179c8.png)

**Comment by yuvadm** [comment]
Yeah I noticed this as well. Added an extra CSS to fix this issue. Pushed new version `v0.4`.

**Comment by shririmps** [comment]
Thanks for the quick reply.  :+1:
